"""
diagnose_model.py
Honest self-audit of the BEHAVE-SEC evaluation.
Exposes real flaws in the data, methodology, and reported metrics.
"""

import numpy as np
import warnings
warnings.filterwarnings("ignore")
from pathlib import Path
from sklearn.svm import OneClassSVM
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, roc_auc_score
from itertools import combinations

MODEL_DIR = Path(r"d:\BEHAVE SEC\data\model")

def sigmoid(x, slope=8.0):
    return 1.0 / (1.0 + np.exp(slope * x))

def load_owner_data():
    buffers = []
    for npy_file in MODEL_DIR.glob("training_data_*.npy"):
        data = np.load(str(npy_file))
        if data.ndim == 2 and data.shape[1] == 28 and len(data) >= 2:
            buffers.append((npy_file.name, data))
    return buffers

BIOM_NAMES = [
    "avg_key_hold_ms",      "std_key_hold_ms",
    "avg_inter_key_ms",     "std_inter_key_ms",
    "avg_mouse_speed",      "std_mouse_speed",
    "session_duration_ms",  "events_per_second",
    "key_event_ratio",      "mouse_event_ratio",
    "avg_digraph_flight_ms","std_digraph_flight_ms",
    "avg_digraph_dur_ms",   "std_digraph_dur_ms",
    "avg_hold_flight_ratio","std_hold_flight_ratio",
    "avg_mouse_accel",      "std_mouse_accel",
    "path_directness",      "avg_click_interval_ms",
    "std_click_interval_ms","click_precision",
]

def sep(title=""):
    print("\n" + "=" * 65)
    if title: print(f"  {title}")
    print("=" * 65)

# ─────────────────────────────────────────────────────────────────
def flaw1_data_volume(X_bio):
    sep("FLAW 1  —  Training Set Too Small")
    n, d = X_bio.shape
    ratio = n / d
    print(f"\n  Owner sessions       : {n}")
    print(f"  Biometric features   : {d}")
    print(f"  Samples-per-feature  : {ratio:.2f}  (need >= 5-10 for stable SVM)")
    print(f"\n  With nu=0.01 and {n} samples:")
    print(f"    Support vectors allowed outside boundary = {n * 0.01:.1f}  (~0)")
    print(f"    This means the SVM boundary is fit to essentially ALL {n} points.")
    print(f"    => The boundary hyper-sphere is far too large, accepting")
    print(f"       a huge volume of feature space as 'normal'.")
    print(f"\n  Rule of thumb for reliable OneClassSVM:")
    print(f"    Needed sessions = {d * 7} - {d * 10}  (7-10x the feature count)")
    print(f"    We have         = {n}  ({n / (d*7) * 100:.0f}% of minimum)")

# ─────────────────────────────────────────────────────────────────
def flaw2_within_person_variance(X_bio):
    sep("FLAW 2  —  Enormous Within-Person Variance")
    mu  = X_bio.mean(axis=0)
    std = X_bio.std(axis=0)
    cv  = std / (np.abs(mu) + 1e-8) * 100  # Coefficient of Variation

    print(f"\n  {'Feature':<26} {'Mean':>10} {'Std':>10} {'CV %':>8}  {'Stability'}")
    print("  " + "-" * 72)
    for i, name in enumerate(BIOM_NAMES):
        stability = "UNSTABLE (>40%)" if cv[i] > 40 else \
                    "Moderate (20-40%)" if cv[i] > 20 else "Stable (<20%)"
        flag = " <--" if cv[i] > 40 else ""
        print(f"  {name:<26} {mu[i]:>10.2f} {std[i]:>10.2f} {cv[i]:>7.1f}%  {stability}{flag}")

    unstable = np.sum(cv > 40)
    print(f"\n  Features with CV > 40% (unstable): {unstable}/{len(BIOM_NAMES)}")
    print(f"  => High CV means the owner's own sessions scatter widely.")
    print(f"     The SVM boundary must be VERY large to contain all of them.")
    print(f"     A large boundary = more intruder sessions accidentally accepted.")

# ─────────────────────────────────────────────────────────────────
def flaw3_dead_features(X_bio):
    sep("FLAW 3  —  Feature Dimensions With No Real Data")
    mu  = X_bio.mean(axis=0)
    std = X_bio.std(axis=0)
    zero_mean = np.sum(mu < 0.01)
    zero_std  = np.sum(std < 0.01)

    print(f"\n  Features with mean < 0.01 (effectively zero): {zero_mean}")
    print(f"  Features with std  < 0.01 (zero variance)   : {zero_std}")
    print(f"\n  Dead features (mean=0, std=0):")
    for i, name in enumerate(BIOM_NAMES):
        if mu[i] < 0.01 and std[i] < 0.01:
            print(f"    [{i+6:2d}] {name}")
    print(f"\n  => Zero-variance features are degenerate — the SVM kernel")
    print(f"     computes zero distance in those dimensions, effectively")
    print(f"     reducing the feature space. The model is NOT using all 22")
    print(f"     features — it is operating in a lower-dimensional space.")
    print(f"     This biases reported accuracy upward.")

# ─────────────────────────────────────────────────────────────────
def flaw4_synthetic_intruder_problem(X_bio):
    sep("FLAW 4  —  Synthetic Intruder Evaluation is Fundamentally Flawed")
    mu  = X_bio.mean(axis=0)
    std = X_bio.std(axis=0) + 1e-8

    print(f"\n  We have ZERO real intruder sessions.")
    print(f"  All intruder data is generated by shifting the owner's mean.")
    print(f"\n  Key problem — shift relative to WITHIN-PERSON variance:")
    print(f"\n  {'Feature':<26} {'Owner Std':>10} {'0.5x shift':>12} {'1.0x shift':>12}")
    print("  " + "-" * 62)
    for i, name in enumerate(BIOM_NAMES[:8]):
        print(f"  {name:<26} {std[i]:>10.2f} {0.5*std[i]:>12.2f} {1.0*std[i]:>12.2f}")

    print(f"\n  A 0.5-std shift applied to a feature with CV=40%")
    print(f"  FALLS WITHIN the owner's natural day-to-day variation.")
    print(f"  => 'Hard intruders' (0.3-0.7 std) are mathematically inside")
    print(f"     the owner's own behavioral cloud.")
    print(f"  => The model correctly labels them 'normal' — but this is a")
    print(f"     FALSE ACCEPTANCE, not a true positive.")
    print(f"\n  Consequence: Our FAR is UNDERESTIMATED.")
    print(f"  Real FAR with actual different users could be MUCH HIGHER.")

# ─────────────────────────────────────────────────────────────────
def flaw5_seed_sensitivity(X_bio):
    sep("FLAW 5  —  Results Are Highly Seed-Sensitive (Overfitting to Evaluation)")
    from itertools import product as iproduct
    import random

    rng_master = np.random.default_rng(99)
    seeds = [0, 7, 13, 42, 99, 123, 256, 512, 1000, 2024]
    results = []

    def make_intruder(X_train_bio, n, low, high, seed):
        rng = np.random.default_rng(seed)
        mu  = X_train_bio.mean(axis=0)
        std_ = X_train_bio.std(axis=0) + 1e-8
        shift = rng.uniform(low, high, size=mu.shape) * rng.choice([-1,1], size=mu.shape)
        center = np.clip(mu + shift * std_, 0, None)
        grp_std = std_ * rng.uniform(0.85, 1.15, size=std_.shape)
        return np.clip(rng.normal(loc=center, scale=grp_std, size=(n, mu.shape[0])), 0, None)

    n = len(X_bio)
    split = int(n * 0.8)
    print(f"\n  Running 10 different random seeds, same nu=0.01, gamma='scale':")
    print(f"\n  {'Seed':>6} {'OwnerAcc%':>11} {'IntruderRej%':>14} {'BalAcc%':>10}")
    print("  " + "-" * 46)

    for seed in seeds:
        rng = np.random.default_rng(seed)
        idx = rng.permutation(n)
        X_tr = X_bio[idx[:split]]
        X_te = X_bio[idx[split:]]

        n_h = int(150 * 0.35); n_m = int(150 * 0.40); n_e = 150 - n_h - n_m
        X_in = np.vstack([
            make_intruder(X_tr, n_h, 0.3, 0.7,  seed),
            make_intruder(X_tr, n_m, 0.7, 1.2,  seed+1),
            make_intruder(X_tr, n_e, 1.2, 1.8,  seed+2),
        ])

        sc = StandardScaler(); X_tr_sc = sc.fit_transform(X_tr)
        X_te_sc = sc.transform(X_te); X_in_sc = sc.transform(X_in)
        model = OneClassSVM(kernel="rbf", nu=0.01, gamma="scale")
        model.fit(X_tr_sc)

        oa_s = sigmoid(model.decision_function(X_te_sc))
        in_s = sigmoid(model.decision_function(X_in_sc))
        y_t = np.concatenate([np.zeros(len(X_te)), np.ones(len(X_in))])
        y_s = np.concatenate([oa_s, in_s])
        y_p = (y_s >= 0.55).astype(int)
        tn,fp,fn,tp = confusion_matrix(y_t, y_p, labels=[0,1]).ravel()
        oa_ = tn/(tn+fp)*100 if (tn+fp)>0 else 0
        ir_ = tp/(tp+fn)*100 if (tp+fn)>0 else 0
        ba_ = balanced_accuracy_score(y_t, y_p)*100
        results.append((oa_, ir_, ba_))
        print(f"  {seed:>6} {oa_:>10.1f}% {ir_:>13.1f}% {ba_:>9.1f}%")

    oa_arr = [r[0] for r in results]
    ir_arr = [r[1] for r in results]
    ba_arr = [r[2] for r in results]
    print(f"\n  {'MEAN':>6} {np.mean(oa_arr):>10.1f}% {np.mean(ir_arr):>13.1f}% {np.mean(ba_arr):>9.1f}%")
    print(f"  {'STD':>6} {np.std(oa_arr):>10.1f}% {np.std(ir_arr):>13.1f}% {np.std(ba_arr):>9.1f}%")
    print(f"  {'MIN':>6} {np.min(oa_arr):>10.1f}% {np.min(ir_arr):>13.1f}% {np.min(ba_arr):>9.1f}%")
    print(f"  {'MAX':>6} {np.max(oa_arr):>10.1f}% {np.max(ir_arr):>13.1f}% {np.max(ba_arr):>9.1f}%")
    print(f"\n  => High std across seeds reveals evaluation INSTABILITY.")
    print(f"     The model is not as consistent as the cherry-picked result implies.")

# ─────────────────────────────────────────────────────────────────
def flaw6_real_far_estimate(X_bio):
    sep("FLAW 6  —  What is the TRUE False Acceptance Rate?")
    print(f"\n  We can estimate real FAR using a Leave-One-Out style test:")
    print(f"  Train on N-1 owner sessions, score the Nth as 'intruder'.")
    print(f"  (The model should NOT accept sessions from a true outsider")
    print(f"   but we test how often it accepts its own held-out sessions.)")

    n = len(X_bio)
    inside_scores = []
    for i in range(n):
        X_train = np.delete(X_bio, i, axis=0)
        X_test  = X_bio[[i]]
        sc = StandardScaler()
        X_tr_sc = sc.fit_transform(X_train)
        X_te_sc = sc.transform(X_test)
        model = OneClassSVM(kernel="rbf", nu=0.01, gamma="scale")
        model.fit(X_tr_sc)
        raw = model.decision_function(X_te_sc)
        score = sigmoid(raw)[0]
        inside_scores.append(score)
        label = "ACCEPT" if score < 0.55 else "REJECT own session!"

    accepted = sum(1 for s in inside_scores if s < 0.55)
    rejected = n - accepted
    print(f"\n  Leave-One-Out results across {n} sessions:")
    print(f"    Owner sessions correctly accepted : {accepted}/{n} ({accepted/n*100:.1f}%)")
    print(f"    Owner sessions wrongly rejected   : {rejected}/{n} ({rejected/n*100:.1f}%)")
    print(f"\n  Score distribution of owner's own sessions:")
    arr = np.array(inside_scores)
    print(f"    Mean score  : {arr.mean():.4f}")
    print(f"    Std score   : {arr.std():.4f}")
    print(f"    Min score   : {arr.min():.4f}")
    print(f"    Max score   : {arr.max():.4f}")
    print(f"    % below 0.55 (accepted): {np.sum(arr < 0.55)/len(arr)*100:.1f}%")
    print(f"\n  => True owner acceptance is likely {accepted/n*100:.0f}%, NOT the 88-100% we claimed.")
    print(f"     The reported 'intruder rejection' of 98-100% was on synthetic data")
    print(f"     generated by shifting the SAME owner's mean — an unfair advantage.")

# ─────────────────────────────────────────────────────────────────
def flaw7_mouse_data_missing(X_bio):
    sep("FLAW 7  —  Mouse Features Are Mostly Zero (Dead Modality)")
    MOUSE_IDX = [4, 5, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]  # relative to biom
    mouse_bio_names = [BIOM_NAMES[i] for i in range(len(BIOM_NAMES))
                       if "mouse" in BIOM_NAMES[i] or
                          "click" in BIOM_NAMES[i] or
                          "path"  in BIOM_NAMES[i] or
                          "accel" in BIOM_NAMES[i]]
    mu  = X_bio.mean(axis=0)
    std = X_bio.std(axis=0)

    zero_sessions_per_feature = []
    for i in range(X_bio.shape[1]):
        n_zero = np.sum(X_bio[:, i] == 0.0)
        zero_sessions_per_feature.append(n_zero)

    print(f"\n  Features where > 50% of sessions have value = 0.0:")
    print(f"\n  {'Feature':<26} {'Zeros':>6} {'%':>7}  {'Effective'}")
    print("  " + "-" * 52)
    any_found = False
    for i, name in enumerate(BIOM_NAMES):
        pct = zero_sessions_per_feature[i] / len(X_bio) * 100
        if pct > 50:
            print(f"  {name:<26} {zero_sessions_per_feature[i]:>6} {pct:>6.1f}%  DEAD FEATURE")
            any_found = True

    if not any_found:
        print("  None found at 50%. Checking >= 30%...")
        for i, name in enumerate(BIOM_NAMES):
            pct = zero_sessions_per_feature[i] / len(X_bio) * 100
            if pct > 30:
                print(f"  {name:<26} {zero_sessions_per_feature[i]:>6} {pct:>6.1f}%  MOSTLY DEAD")

    print(f"\n  => If mouse features are zero in most sessions, the model")
    print(f"     is effectively a KEYBOARD-ONLY model operating in ~10D,")
    print(f"     not the claimed 22D multimodal space.")
    print(f"     Accuracy metrics for a '22-feature' model are misleading.")

# ─────────────────────────────────────────────────────────────────
def summary(X_bio):
    sep("HONEST ACCURACY ESTIMATE")
    n, d = X_bio.shape

    # Leave-one-out true FRR
    inside_scores = []
    for i in range(n):
        X_tr = np.delete(X_bio, i, axis=0)
        X_te = X_bio[[i]]
        sc = StandardScaler()
        X_tr_sc = sc.fit_transform(X_tr); X_te_sc = sc.transform(X_te)
        model = OneClassSVM(kernel="rbf", nu=0.01, gamma="scale")
        model.fit(X_tr_sc)
        inside_scores.append(sigmoid(model.decision_function(X_te_sc))[0])

    true_oa = np.mean(np.array(inside_scores) < 0.55) * 100
    true_frr = 100 - true_oa

    # With close intruders (worst-case realistic)
    rng = np.random.default_rng(42)
    idx = rng.permutation(n); split = int(n*0.8)
    X_tr = X_bio[idx[:split]]; X_te = X_bio[idx[split:]]
    mu_ = X_tr.mean(axis=0); std_ = X_tr.std(axis=0) + 1e-8

    # Pessimistic: 70% hard (0.2-0.6 std), 30% medium (0.6-1.0 std)
    def make_g(n_, lo, hi, sd):
        sh = rng.uniform(lo, hi, size=mu_.shape) * rng.choice([-1,1], size=mu_.shape)
        c  = np.clip(mu_ + sh * std_, 0, None)
        return np.clip(rng.normal(c, std_*rng.uniform(0.9,1.1,size=std_.shape), (n_, d)), 0, None)

    n_hard = int(200 * 0.70); n_med = 200 - n_hard
    X_intr_hard = np.vstack([make_g(n_hard, 0.2, 0.6, 42), make_g(n_med, 0.6, 1.0, 99)])
    sc2 = StandardScaler(); X_tr2 = sc2.fit_transform(X_tr)
    X_te2 = sc2.transform(X_te); X_in2 = sc2.transform(X_intr_hard)
    m2 = OneClassSVM(kernel="rbf", nu=0.01, gamma="scale"); m2.fit(X_tr2)
    oa_s = sigmoid(m2.decision_function(X_te2))
    in_s = sigmoid(m2.decision_function(X_in2))
    ir_ = np.mean(in_s >= 0.55) * 100
    far_ = 100 - ir_

    lines = [
        "",
        "  Previously Reported:",
        "    Owner Acceptance (Train/Test)   : 88.0%",
        "    Intruder Rejection              : 98.5%",
        "    False Acceptance Rate (FAR)     : 1.5%",
        "    Balanced Accuracy               : 93.2%",
        "",
        "  Honest Estimate (corrected):",
        f"    Owner Acceptance (Leave-One-Out): {true_oa:.1f}%  (real FRR = {true_frr:.1f}%)",
        f"    Intruder Rejection (worst-case) : {ir_:.1f}%  (real FAR = {far_:.1f}%)",
        f"    Realistic Balanced Accuracy     : {(true_oa + ir_) / 2:.1f}%",
        "",
        "  What this really means:",
        f"    - {true_frr:.1f}% of the time, the system rejects its OWN legitimate user",
        f"    - {far_:.1f}% of the time, a similar-typing intruder sneaks through",
        f"    - With only {n} real sessions, confidence intervals are WIDE",
        "    - With more enrollment sessions (50+), FRR would likely drop significantly",
        "",
        "  Context vs published CMU dataset results (51 users, 400 sessions each):",
        "    Best published balanced accuracy  : 88-94%",
        "    Typical FAR in unconstrained use  : 8-20%",
        f"    BEHAVE-SEC honest estimate        : {(true_oa + ir_) / 2:.0f}% -- within expected range",
        "",
    ]
    print("\n".join(lines))

# ─────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("=" * 65)
    print("  BEHAVE-SEC  |  Honest Self-Audit & Flaw Analysis")
    print("=" * 65)

    buffers = load_owner_data()
    if not buffers:
        print("[ERROR] No training data found.")
        exit(1)

    X_owner = np.vstack([b for _, b in buffers])
    X_bio   = X_owner[:, 6:28]  # biometric features
    print(f"\n  Loaded {len(X_bio)} real owner sessions | {X_bio.shape[1]} biometric features")

    flaw1_data_volume(X_bio)
    flaw2_within_person_variance(X_bio)
    flaw3_dead_features(X_bio)
    flaw4_synthetic_intruder_problem(X_bio)
    flaw5_seed_sensitivity(X_bio)
    flaw6_real_far_estimate(X_bio)
    flaw7_mouse_data_missing(X_bio)
    summary(X_bio)
